name: chamdiemtudong
description: Your project description
publish_to: 'none' # Remove this line if you're publishing

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0+1  # Cập nhật lên phiên bản mới nhất
  image_picker: ^0.8.9
  http: ^0.13.3
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
